"""장 구분/세션 상수 (KRX 정규세션, NXT 애프터마켓, 의사결정 듀얼벤뉴)."""

from __future__ import annotations

KRX_CLOSE_MARKET_DIV_CODE: str = "J"
NXT_MARKET_DIV_CODE: str = "NX"
DECISION_WINDOW_START_HHMMSS: str = "152000"
DECISION_WINDOW_END_HHMMSS: str = "153000"
# 정수형 비교용 파생값 (문자열과 드리프트 방지)
DECISION_WINDOW_START_HMS: int = int(DECISION_WINDOW_START_HHMMSS)
# 정수형 비교용 파생값 (문자열과 드리프트 방지)
DECISION_WINDOW_END_HMS: int = int(DECISION_WINDOW_END_HHMMSS)
DEFAULT_BAR_INTERVAL_MINUTES: int = 1
INTRADAY_SESSION_REGULAR: str = "regular"
INTRADAY_SESSION_NXT_AFTERMARKET: str = "nxt_aftermarket"
INTRADAY_SESSION_NXT_PREMARKET: str = "nxt_premarket"
KRX_REGULAR_HOUR_FLOOR: str = "090000"
KRX_REGULAR_HOUR_CEIL: str = "153000"
NXT_AFTERMARKET_HOUR_FLOOR: str = "154000"
NXT_AFTERMARKET_HOUR_CEIL: str = "200000"
NXT_PREMARKET_HOUR_FLOOR: str = "080000"
NXT_PREMARKET_HOUR_CEIL: str = "085000"
